repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: flake8
      name: flake8 (code linting)
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      name: black (code formatting)
      language_version: python3.8
-   repo: local
    hooks:
    - id: mypy
      name: mypy (static typing)
      pass_filenames: false
      language: script
      entry: ci/run_mypy.sh
      verbose: true
