codeCheckStep: &codeCheckStep
  step:
    name: Code check
    image: python:3.8.3
    script:
      # Running pre-commit, as it is repeatable from repo code
      - pip install pre-commit==2.2.0
      - pre-commit run --all-files --show-diff-on-failure

buildAndTestStep: &buildAndTestStep
  step:
    name: Build and Test
    image: python:3.8.3
    caches:
        - pip
    script:
        - ci/SETUP.sh
        - apt-get update
        - apt-get -y install postgresql-client coinor-cbc
        - PGPASSWORD=flexmeasures_test psql -h localhost -p 5432 -c "create extension if not exists cube; create extension if not exists earthdistance;" -U flexmeasures_test flexmeasures_test;
        - make install-deps
        - make test
    services:
        - postgres

pipelines:
  default:
    - <<: *codeCheckStep
    - <<: *buildAndTestStep

  branches:
    master:
      - <<: *codeCheckStep
      - <<: *buildAndTestStep
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - ci/DEPLOY.sh

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: flexmeasures_test
        POSTGRES_USER: flexmeasures_test
        POSTGRES_PASSWORD: flexmeasures_test
        DATABASE_URL: postgres://flexmeasures_test:flexmeasures_test@127.0.0.1:5432/flexmeasures_test
