pipelines:
  default:
    - step:
        name: Lint by Flake8
        image: python:3.6
        script:
            - pip install flake8-bugbear flake8
            - flake8 bvp
    - step:
        name: Build and Test
        image: python:3.6
        caches:
          - pip
        script:
          - ci/SETUP.sh
          - apt-get update
          - apt-get -y install postgresql-client
          - PGPASSWORD=a1test psql -h localhost -p 5432 -c "create extension if not exists cube; create extension if not exists earthdistance;" -U a1test a1test;
          - python setup.py test
        services:
          - postgres
  branches:
    master:
      - step:
          name: Build and Test
          image: python:3.6
          script:
            - ci/SETUP.sh
            - python setup.py test
          caches:
            - pip
          services:
            - postgres
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - ci/DEPLOY.sh

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: a1test
        POSTGRES_USER: a1test
        POSTGRES_PASSWORD: a1test
        DATABASE_URL: postgres://a1test:a1test@127.0.0.1:5432/a1test